### ISSUE TITLE
Repositories page shows missing values for DataTypes/Strategy 

### ISSUE THREAD

**Issue by rtisma** [icgc-dcc/dcc-repository#32] opened 2018-11-14 15:40 UTC
Create this filter:  Collab, PCAWG, No Data

this is most likely a merge issue in the dcc-repository.

**Comment by junjun-zhang** [comment] 2018-11-15 01:28
Among your tasks in this sprint, can you please give this a priority? It seems there are more problems than just missing values. See: https://icgc.org/ZrV, these are supposed to be Aligned Reads, but are incorrectly shown as Unaligned Reads.

This will be addressed by updating the SONG payloads (internal ticket: DCCBIO-83).

**Comment by rtisma** [comment] 2018-11-19 17:16
@junjun-zhang after analyzing the code, it seems that the `experiment.aligned` field is not defined. the dcc-repository indexer looks for that field and since it is not defined, it is treated as not aligned.

The best option is to update the experiment portion of the analysis. This will require a new endpoint, and i will deliver that, however many of the analyses need to be updated.

**Comment by rtisma** [comment] 2018-11-19 17:28
this ticket is blocked by overture-stack/song#368

**Comment by Fgerthoffert** [comment] 2018-11-28 16:39
@junjun-zhang check this out first

**Comment by junjun-zhang** [comment] 2018-12-04 15:21
There are two separate problems here:
- first: some BAM files are incorrectly marked as `Unaligned Reads`, the root cause is that the `experiment.aligned` flag is not set in SONG payload. The fix is to populate it, which depends on overture-stack/song#368
- the second problem is what this ticket was initially created for: *missing values for DataTypes/Strategy*

This github issue should be used to track/address the second problem, not the first one.

**Comment by rtisma** [comment] 2018-12-04 18:49
@junjun-zhang i think you are right and i mixed things up. Can you check if the DataTypes/Strategy error still exists? I tried to replicate the issue, and I couldnt.

**Closed as completed** 2018-12-07 21:20 UTC
Labels: bug, SP:3
